### ISSUE TITLE
Ruby: "Expression should be on its own line" vs "Line is too long"

### ISSUE THREAD

**Issue by ldlsegovia** [platanus/hound#3]
Me pasó esto: tengo esta línea

``` ruby
it { expect { @notifier.notify }.to_not change(
  user_product.transactions.with_status(:notified), :size) }
```

y me salió esto: `Expression at 41, 68 should be on its own line.` Cuando pongo el código en una línea, el mono me reta con `Line is too long. [111/100]`

No me gusta tener que hacer esto:

``` ruby
it "some redundant explanation" do
  notified_transactions = user_product.transactions.with_status(:notified)
  expect { @notifier.notify }.to_not change(notified_transactions, :size)
end
```

sólo porque la línea es larga...

Cuál creen que es la solución?

**Comment by blackjid** [comment]
@juliogarciag que opina??

a mi igual me gusta más lo que tu pusiste que no te gusta :grin:

**Comment by juliogarciag** [comment]
La verdad opino lo mismo que el negro. `it { expect(x).to matcher(arguments)` se me hace medio raro de leer. No por ser más corto me parece más conciso. Por otro lado, los mensajes de los tests en el reporte de rspec en el caso de usar `change` son, que recuerde, muy poco explicativos si no usas una explicación redundante en `it`.

**Comment by ldlsegovia** [comment]
Suficiente para mí. Lo hacemos como en la opción 3

**Comment by juliogarciag** [comment]
@ldlsegovia ¿Crees que debamos cerrar esta issue?

**Comment by ldlsegovia** [comment]
cierro!
