### ISSUE TITLE
Ignorar ciertos archivos

### ISSUE THREAD

**Issue by ldlsegovia** [platanus/hound#4]
<img width="788" alt="screen shot 2015-09-24 at 10 39 11 am" src="https://cloud.githubusercontent.com/assets/3026413/10074864/cdf3d634-62a8-11e5-92c3-fe5a6115fb05.png">

@blackjid se puede configurar que se ignoren algunos archivos autogenerados?

**Comment by blackjid** [comment]
@ldlsegovia si se puede.. hay dos alternativas...

Si es algo muy generico, debieramos agregarlos en el archivo de reglas de estilo
https://github.com/platanus/hound/blob/platanus/config/style_guides/platanus/ruby.yml#L6

Si es algo particular del proyecto, se puede agregar un `ruby-style.yml` al proyecto con los exclude.
Abria que tambien agregar un `.hound.yml` donde se especifica cual es el archivo de configuracion para los chekeos de ruby.

``` yml
ruby:
  config_file: .ruby-style.yml
```

Hound hace merge de ese archivo con los default.. (ahora esto va a cambiar pronto y ya no va a hacer merge)

**Comment by ldlsegovia** [comment]
genial, creo que el `schema.rb` tiene que estar ignorado por defecto

**Comment by juliogarciag** [comment]
Sí, bueno, sería bueno un PR agregando que se ignore todo lo que está dentro de `db/`

**Comment by blackjid** [comment]
be my guest!

**Comment by blackjid** [comment]
bah!, en teoria estan excluidos...
vamos a investigar
https://github.com/platanus/hound/blob/platanus/config/style_guides/platanus/ruby.yml#L8

**Comment by blackjid** [comment]
a no... le faltarian unos `**` antes...

**Comment by juliogarciag** [comment]
Acabo de correr `rubocop` sobre un proyecto que usa el rubocop.yml de hound y no me lista los errores en `db/schema.rb`, que son varios, ni algunos agregados al vuelo en las migraciones (lo cual está bien). Ahora, no he hecho que hound lo revise así que tendría que ver porque podría ser un problema específico de hound.
- Sobre lo que cerré y reabrí la issue, sólo quería comentar y equivoqué el botón.
