### ISSUE TITLE
Should we activate `UseHashRocketsWithSymbolValues`?

### ISSUE THREAD

**Issue by juliogarciag** [platanus/hound#5]
This is a matter of taste but some gems (`state_machine`) for example, use hash rockets to represent some relationships between symbols:

``` ruby
event :approve do
  transition :pending => :approved
end
```

And i find it more readable than:

``` ruby
event :approve do
  transition pending: :approved
end
```

It only take effects with values that are symbols, not arrays, objects, numbers or strings.

The rationale behind the option is in [this issue in rubocop](https://github.com/bbatsov/rubocop/issues/1437).

**Comment by blackjid** [comment]
:+1:

**Comment by juliogarciag** [comment]
Now I think, after some usage on one project and no-usage in another ones, that this property is not so interesting because it can lead to inconsistencies and changes in cases where the arrow doesn't provide a lot of value (i found the state machine definition to be the only example of this). If somebody thinks this is important or we should have to do this, this issue will be reopened then.
