### ISSUE TITLE
Actualizar Rubocop

### ISSUE THREAD

**Issue by juliogarciag** [platanus/hound#6]
Rubocop ha hecho release de una versión que ha agregado/renombrado/eliminado varios cops (nos topamos el problema en surbtc porque el servidor de CI instalaba el último rubocop y un día X comenzó a dar multitud de errores). Por lo que veo, en thoughtbot/hound han actualizado ya: https://github.com/thoughtbot/hound/pull/1034. @blackjid ¿Deberíamos mezclar de ahí?

**Comment by blackjid** [comment]
@juliogarciag ya actualize hound y estamos al dia con los commits de thoughtbot.
Avisame si vez que algo no anda bien.
